---
- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: present

- name: Enable and start Redis service
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: yes
